// <auto-generated />
using System;
using Mapper.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mapper.Persistence.Migrations
{
    [DbContext(typeof(MapperDbContext))]
    [Migration("20251227173520_InitialMapperDb")]
    partial class InitialMapperDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mapper.Domain.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cabinet")
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<Guid?>("EmployeePhotoId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GeoMarkId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmployeePhotoId");

                    b.HasIndex("GeoMarkId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Mapper.Domain.EmployeePhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("EmployeePhoto");
                });

            modelBuilder.Entity("Mapper.Domain.GeoMap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("ImageHeight")
                        .HasColumnType("integer");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ImageWidth")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("geo_maps", (string)null);
                });

            modelBuilder.Entity("Mapper.Domain.GeoMark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("GeoMapId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<double>("X")
                        .HasColumnType("double precision");

                    b.Property<double>("Y")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("GeoMapId");

                    b.ToTable("geo_marks", (string)null);

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Mapper.Domain.WorkplaceEmployee", b =>
                {
                    b.Property<Guid>("WorkplaceMarkId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.HasKey("WorkplaceMarkId", "EmployeeId");

                    b.ToTable("workplace_employees", (string)null);
                });

            modelBuilder.Entity("Mapper.Domain.CameraMark", b =>
                {
                    b.HasBaseType("Mapper.Domain.GeoMark");

                    b.Property<string>("CameraName")
                        .HasColumnType("text");

                    b.Property<string>("StreamUrl")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Mapper.Domain.TransitionMark", b =>
                {
                    b.HasBaseType("Mapper.Domain.GeoMark");

                    b.Property<Guid>("TargetGeoMapId")
                        .HasColumnType("uuid");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Mapper.Domain.WorkplaceMark", b =>
                {
                    b.HasBaseType("Mapper.Domain.GeoMark");

                    b.Property<string>("WorkplaceCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Mapper.Domain.Employee", b =>
                {
                    b.HasOne("Mapper.Domain.EmployeePhoto", "EmployeePhoto")
                        .WithMany()
                        .HasForeignKey("EmployeePhotoId");

                    b.HasOne("Mapper.Domain.GeoMark", "GeoMark")
                        .WithMany()
                        .HasForeignKey("GeoMarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeePhoto");

                    b.Navigation("GeoMark");
                });

            modelBuilder.Entity("Mapper.Domain.GeoMark", b =>
                {
                    b.HasOne("Mapper.Domain.GeoMap", null)
                        .WithMany("Marks")
                        .HasForeignKey("GeoMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mapper.Domain.WorkplaceEmployee", b =>
                {
                    b.HasOne("Mapper.Domain.WorkplaceMark", null)
                        .WithMany("Employees")
                        .HasForeignKey("WorkplaceMarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mapper.Domain.GeoMap", b =>
                {
                    b.Navigation("Marks");
                });

            modelBuilder.Entity("Mapper.Domain.WorkplaceMark", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
