# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches:
      - '*'  # Run on all branches
  pull_request:
    branches:
      - 'master'  # Run on pull requests targeting 'master' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Main job runs on Ubuntu

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      # Restore project dependencies
      - name: Restore dependencies
        run: dotnet restore Mapper.sln

      # Build the solution
      - name: Build the solution
        run: dotnet build Mapper.sln --configuration Release --no-restore

      # Run tests with code coverage
      - name: Run tests
        run: dotnet test src/Mapper.Tests/Mapper.Tests.csproj --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

      # Install ReportGenerator tool
      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      # Generate coverage report
      - name: Generate coverage report
        run: reportgenerator -reports:./coverage/**/coverage.cobertura.xml -targetdir:./coverage/report -reporttypes:Html;MarkdownSummaryGithub

      # Upload coverage report as artifact
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./coverage/report

      # Display coverage summary in GitHub Actions
      - name: Add coverage summary to PR
        run: cat ./coverage/report/SummaryGithub.md >> $GITHUB_STEP_SUMMARY

